/* Requires the Docker Pipeline plugin */
pipeline {
    agent { 
        docker {
            image 'python:3.13.3-alpine3.21' 
            args '-v $HOME:/usr/src -w /usr/src/.jenkins/workspace/MyPipeline_main/'
        } 
    }
    stages {
        stage('build') {
            steps {
                sh 'cd /usr/src; ls -l'
            }
        }
    }
}

