pipeline {
    agent { any { image 'python:3.13.3-alpine3.21' } }
    stages {
        stage('build') {
            steps {
                bat 'docker-compose -f docker-compose.yml up -d'
            }
        }
    }
}
